-- =============================================
-- Claw Clash: Agent Chat System (Pre-generation)
-- =============================================

-- Agent chat response pool (pre-generated by LLM before battle)
CREATE TABLE agent_chat_pool (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    game_id UUID NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    agent_id UUID NOT NULL REFERENCES agents(id),
    responses JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(game_id, agent_id)
);

CREATE INDEX idx_agent_chat_pool_game ON agent_chat_pool(game_id);

-- Extend game_chat msg_type to include AI chat types
ALTER TABLE game_chat DROP CONSTRAINT IF EXISTS game_chat_msg_type_check;
ALTER TABLE game_chat ADD CONSTRAINT game_chat_msg_type_check
    CHECK (msg_type IN ('ai_strategy', 'ai_taunt', 'ai_chat', 'human_chat', 'system'));

-- Add emotion column to game_chat
ALTER TABLE game_chat ADD COLUMN IF NOT EXISTS emotion VARCHAR(20);
